SIZE = 30
WIDTH = 10
HEIGHT = 20
BORDER = 1
NEXT_FIGURE_RECT_SIZE = 15

TOP_LEFT_INSERT_POINT = WIDTH // 2 - 2

CANVAS_WIDTH = SIZE * WIDTH + 1
CANVAS_HEIGHT = SIZE * HEIGHT + 1

SIDE_PANEL_WIDTH = 200
SIDE_PANEL_HEIGHT = CANVAS_HEIGHT

NEXT_FIGURE_CANVAS_WIDTH = NEXT_FIGURE_RECT_SIZE * 4 + 11
NEXT_FIGURE_CANVAS_HEIGHT = NEXT_FIGURE_RECT_SIZE * 4 + 11

CONTAINER_WIDTH = CANVAS_WIDTH + 6 + SIDE_PANEL_WIDTH
CONTAINER_HEIGHT = CANVAS_HEIGHT + 6

LEVEL_1_INTERVAL = 1
SPEED_INCREASE_COEFF = 0.9
SCORE_INCREASE_COEFF = 1.1

IN_GAME = 0
GAME_PAUSED = 1
GAME_ENDED = 2

COEFF = 100

POINTS = {
    1: int(1.0 * COEFF),
    2: int(2.5 * COEFF),
    3: int(5.0 * COEFF),
    4: int(8.0 * COEFF),
    'tetris': int(12.0 * COEFF)
}
